// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *company → Links*
 */
export interface CompanyDocumentDataLinksItem {
  /**
   * Link Text field in *company → Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Link Text label
   * - **API ID Path**: company.links[].link_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_text: prismic.KeyTextField;

  /**
   * Link field in *company → Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link
   * - **API ID Path**: company.links[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Content for company documents
 */
interface CompanyDocumentData {
  /**
   * Name field in *company*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Company name
   * - **API ID Path**: company.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.RichTextField;

  /**
   * Logo field in *company*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: company.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Website field in *company*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Compagny website
   * - **API ID Path**: company.website
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  website: prismic.LinkField;

  /**
   * Card Image field in *company*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: company.card_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  card_image: prismic.ImageField<never>;

  /**
   * Description field in *company*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Description
   * - **API ID Path**: company.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Call To Action field in *company*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: CTA labe
   * - **API ID Path**: company.call_to_action
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  call_to_action: prismic.RichTextField;

  /**
   * Call To Action Link field in *company*
   *
   * - **Field Type**: Link
   * - **Placeholder**: CTA link
   * - **API ID Path**: company.call_to_action_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  call_to_action_link: prismic.LinkField;

  /**
   * Discord field in *company*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Discord Link
   * - **API ID Path**: company.discord
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  discord: prismic.LinkField;

  /**
   * Tier field in *company*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Tier
   * - **API ID Path**: company.tier
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  tier: prismic.SelectField<'gold' | 'diamond'>;

  /**
   * Tier Rank field in *company*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Tier Rank
   * - **API ID Path**: company.tier_rank
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  tier_rank: prismic.NumberField;

  /**
   * Links field in *company*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: company.links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  links: prismic.GroupField<Simplify<CompanyDocumentDataLinksItem>>;

  /**
   * Youtube Slug field in *company*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Youtube Slug
   * - **API ID Path**: company.youtube_slug
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  youtube_slug: prismic.KeyTextField;
}

/**
 * company document from Prismic
 *
 * - **API ID**: `company`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CompanyDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
  Simplify<CompanyDocumentData>,
  'company',
  Lang
>;

/**
 * Content for job documents
 */
interface JobDocumentData {
  /**
   * Title field in *job*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Job title
   * - **API ID Path**: job.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Company Name field in *job*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Company Name
   * - **API ID Path**: job.company_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  company_name: prismic.RichTextField;

  /**
   * Description field in *job*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Job description
   * - **API ID Path**: job.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Link field in *job*
   *
   * - **Field Type**: Link
   * - **Placeholder**: External Link
   * - **API ID Path**: job.link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Discord field in *job*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: job.discord
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  discord: prismic.LinkField;

  /**
   * Rank field in *job*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: job.rank
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  rank: prismic.NumberField;
}

/**
 * job document from Prismic
 *
 * - **API ID**: `job`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type JobDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
  Simplify<JobDocumentData>,
  'job',
  Lang
>;

/**
 * Content for Speaker documents
 */
interface SpeakerDocumentData {
  /**
   * Name field in *Speaker*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Speaker's name
   * - **API ID Path**: speaker.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.RichTextField;

  /**
   * Image field in *Speaker*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: speaker.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *Speaker*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Role
   * - **API ID Path**: speaker.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Company field in *Speaker*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Company
   * - **API ID Path**: speaker.company
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  company: prismic.RichTextField;

  /**
   * Bio field in *Speaker*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Bio
   * - **API ID Path**: speaker.bio
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  bio: prismic.RichTextField;

  /**
   * Twitter field in *Speaker*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Twitter profile URL
   * - **API ID Path**: speaker.twitter
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  twitter: prismic.LinkField;

  /**
   * Github field in *Speaker*
   *
   * - **Field Type**: Link
   * - **Placeholder**: GitHub profile URL
   * - **API ID Path**: speaker.github
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  github: prismic.LinkField;

  /**
   * Talk field in *Speaker*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: speaker.talk
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  talk: prismic.LinkToMediaField;
}

/**
 * Speaker document from Prismic
 *
 * - **API ID**: `speaker`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SpeakerDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
  Simplify<SpeakerDocumentData>,
  'speaker',
  Lang
>;

/**
 * Item in *stage → Schedule*
 */
export interface StageDocumentDataScheduleItem {
  /**
   * Talk field in *stage → Schedule*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: stage.schedule[].talk
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  talk: prismic.LinkField;
}

/**
 * Content for stage documents
 */
interface StageDocumentData {
  /**
   * Name field in *stage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: stage.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.RichTextField;

  /**
   * Stream field in *stage*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: stage.stream
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  stream: prismic.LinkField;

  /**
   * Discord field in *stage*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: stage.discord
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  discord: prismic.LinkField;

  /**
   * Schedule field in *stage*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: stage.schedule[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  schedule: prismic.GroupField<Simplify<StageDocumentDataScheduleItem>>;

  /**
   * isLive field in *stage*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: stage.islive
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  islive: prismic.BooleanField;

  /**
   *  roomId field in *stage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: rooom id 100ms
   * - **API ID Path**: stage.roomid
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  roomid: prismic.KeyTextField;

  /**
   * backstagePeers field in *stage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: stage.backstagepeers
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  backstagepeers: prismic.KeyTextField;

  /**
   * stagePeers field in *stage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: stage.stagepeers
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  stagepeers: prismic.KeyTextField;
}

/**
 * stage document from Prismic
 *
 * - **API ID**: `stage`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type StageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
  Simplify<StageDocumentData>,
  'stage',
  Lang
>;

/**
 * Item in *talk → Speakers*
 */
export interface TalkDocumentDataSpeakersItem {
  /**
   * Speaker field in *talk → Speakers*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: talk.speakers[].speaker
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  speaker: prismic.ContentRelationshipField<'speaker'>;
}

/**
 * Content for talk documents
 */
interface TalkDocumentData {
  /**
   * Title field in *talk*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Talk title
   * - **API ID Path**: talk.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Speakers field in *talk*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: talk.speakers[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  speakers: prismic.GroupField<Simplify<TalkDocumentDataSpeakersItem>>;

  /**
   * Start field in *talk*
   *
   * - **Field Type**: Timestamp
   * - **Placeholder**: *None*
   * - **API ID Path**: talk.start
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#timestamp
   */
  start: prismic.TimestampField;

  /**
   * End field in *talk*
   *
   * - **Field Type**: Timestamp
   * - **Placeholder**: *None*
   * - **API ID Path**: talk.end
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#timestamp
   */
  end: prismic.TimestampField;

  /**
   * Description field in *talk*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Talk description
   * - **API ID Path**: talk.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * talk document from Prismic
 *
 * - **API ID**: `talk`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TalkDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
  Simplify<TalkDocumentData>,
  'talk',
  Lang
>;

export type AllDocumentTypes =
  | CompanyDocument
  | JobDocument
  | SpeakerDocument
  | StageDocument
  | TalkDocument;

declare module '@prismicio/client' {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      CompanyDocument,
      CompanyDocumentData,
      CompanyDocumentDataLinksItem,
      JobDocument,
      JobDocumentData,
      SpeakerDocument,
      SpeakerDocumentData,
      StageDocument,
      StageDocumentData,
      StageDocumentDataScheduleItem,
      TalkDocument,
      TalkDocumentData,
      TalkDocumentDataSpeakersItem,
      AllDocumentTypes
    };
  }
}
